package resolvconf

import (
	"bufio"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"strings"
	"time"
)

const DefaultPath = "/etc/resolv.conf"

// Config is a simplified view of resolv.conf.
type Config struct {
	Path        string
	Nameservers []string
	Search      []string
	// Other lines (options, sortlist, comments we preserve optionally — we regenerate cleanly)
	SymlinkTarget string // non-empty if Path is a symlink
}

// Load reads resolv.conf (follows symlink for content; records link target).
func Load(path string) (*Config, error) {
	if path == "" {
		path = DefaultPath
	}
	c := &Config{Path: path}
	if fi, err := os.Lstat(path); err == nil && fi.Mode()&os.ModeSymlink != 0 {
		if target, err := os.Readlink(path); err == nil {
			c.SymlinkTarget = target
		}
	}
	f, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return c, nil
		}
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	defer f.Close()

	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, ";") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 2 {
			continue
		}
		switch strings.ToLower(fields[0]) {
		case "nameserver":
			c.Nameservers = append(c.Nameservers, fields[1])
		case "search":
			c.Search = append(c.Search, fields[1:]...)
		case "domain":
			// Treat domain as a single-entry search for editing simplicity.
			if len(c.Search) == 0 {
				c.Search = append(c.Search, fields[1])
			}
		}
	}
	return c, sc.Err()
}

// Validate checks nameserver addresses.
func (c *Config) Validate() error {
	if c == nil {
		return fmt.Errorf("config is nil")
	}
	if len(c.Nameservers) == 0 {
		return fmt.Errorf("at least one nameserver is required")
	}
	for _, ns := range c.Nameservers {
		ns = strings.TrimSpace(ns)
		if ns == "" {
			continue
		}
		if net.ParseIP(ns) == nil {
			return fmt.Errorf("invalid nameserver address %q", ns)
		}
	}
	return nil
}

// Render produces resolv.conf content.
func (c *Config) Render() string {
	var b strings.Builder
	b.WriteString("# Generated by debian-network-tui\n")
	for _, ns := range c.Nameservers {
		ns = strings.TrimSpace(ns)
		if ns == "" {
			continue
		}
		b.WriteString("nameserver " + ns + "\n")
	}
	if len(c.Search) > 0 {
		var parts []string
		for _, s := range c.Search {
			s = strings.TrimSpace(s)
			if s != "" {
				parts = append(parts, s)
			}
		}
		if len(parts) > 0 {
			b.WriteString("search " + strings.Join(parts, " ") + "\n")
		}
	}
	return b.String()
}

// Save writes resolv.conf atomically after backup. Replaces a symlink with a regular file.
func (c *Config) Save() error {
	if err := c.Validate(); err != nil {
		return err
	}
	path := c.Path
	if path == "" {
		path = DefaultPath
	}
	if err := backup(path); err != nil {
		return err
	}
	// If path is a symlink, remove it so we write a real file.
	if fi, err := os.Lstat(path); err == nil && fi.Mode()&os.ModeSymlink != 0 {
		if err := os.Remove(path); err != nil {
			return fmt.Errorf("remove symlink %s: %w", path, err)
		}
	}
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".resolv.conf-*.tmp")
	if err != nil {
		return fmt.Errorf("create temp file: %w", err)
	}
	tmpName := tmp.Name()
	defer func() { _ = os.Remove(tmpName) }()

	if _, err := tmp.WriteString(c.Render()); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("write temp file: %w", err)
	}
	_ = tmp.Chmod(0o644)
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Rename(tmpName, path); err != nil {
		return fmt.Errorf("replace %s: %w", path, err)
	}
	return nil
}

func backup(path string) error {
	_, err := backupTo(path)
	return err
}

func backupTo(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", fmt.Errorf("backup read: %w", err)
	}
	bak := fmt.Sprintf("%s.bak.%s", path, time.Now().Format("20060102-150405"))
	if err := os.WriteFile(bak, data, 0o644); err != nil {
		return "", err
	}
	return bak, nil
}

// FindLocalConfigs looks for a resolv.conf template next to the binary.
func FindLocalConfigs(dir string) ([]string, error) {
	var out []string
	seen := map[string]struct{}{}
	add := func(p string) {
		if _, ok := seen[p]; ok {
			return
		}
		seen[p] = struct{}{}
		out = append(out, p)
	}
	for _, name := range []string{"resolv.conf", "dns-resolv.conf", "dns.conf"} {
		p := filepath.Join(dir, name)
		if st, err := os.Stat(p); err == nil && !st.IsDir() {
			add(p)
		}
	}
	entries, err := os.ReadDir(dir)
	if err == nil {
		for _, e := range entries {
			if e.IsDir() {
				continue
			}
			n := strings.ToLower(e.Name())
			if strings.HasPrefix(n, "resolv.conf.") && !strings.Contains(n, ".bak.") {
				add(filepath.Join(dir, e.Name()))
			}
		}
	}
	return out, nil
}

// OverwriteFromFile replaces dest with the exact contents of src (after backup).
// Symlinks at dest are removed so a regular file is written.
func OverwriteFromFile(src, dest string) (backupPath string, err error) {
	if dest == "" {
		dest = DefaultPath
	}
	data, err := os.ReadFile(src)
	if err != nil {
		return "", fmt.Errorf("read %s: %w", src, err)
	}
	if len(strings.TrimSpace(string(data))) == 0 {
		return "", fmt.Errorf("%s is empty", src)
	}
	// Light validation: at least one nameserver line if the file looks like resolv.conf.
	cfg, loadErr := Load(src)
	if loadErr == nil && len(cfg.Nameservers) == 0 {
		return "", fmt.Errorf("%s has no nameserver lines", src)
	}

	bak, err := backupTo(dest)
	if err != nil {
		return "", err
	}
	if fi, err := os.Lstat(dest); err == nil && fi.Mode()&os.ModeSymlink != 0 {
		if err := os.Remove(dest); err != nil {
			return bak, fmt.Errorf("remove symlink %s: %w", dest, err)
		}
	}
	dir := filepath.Dir(dest)
	tmp, err := os.CreateTemp(dir, ".resolv.conf-*.tmp")
	if err != nil {
		return bak, fmt.Errorf("create temp file: %w", err)
	}
	tmpName := tmp.Name()
	defer func() { _ = os.Remove(tmpName) }()

	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return bak, fmt.Errorf("write temp file: %w", err)
	}
	_ = tmp.Chmod(0o644)
	if err := tmp.Close(); err != nil {
		return bak, err
	}
	if err := os.Rename(tmpName, dest); err != nil {
		return bak, fmt.Errorf("replace %s: %w", dest, err)
	}
	return bak, nil
}
